"""
Django settings for sena project.

Generated by 'django-admin startproject' using Django 4.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent#Esta variable se queda con la ruta del proyecto


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_r7vitb=_tt3lhpe^n1f^ar4xhcd9!725ftpq9kxdsc)!lwf5l'#Permite trabajar objetos de seguridas, es un hass(?) y permite verificar contraseñas y formularios 

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True#Brinda un servidor de prueba y muestra todas las trazas de errores, cuando está el false es porque se va a instalar

ALLOWED_HOSTS = []#Solo lo puedo navegar yo, dentro de [ ] van las direcciones ip con las cuales se puede compartir, pero si quiero que todo internet entre le pongo *


# Application definition

INSTALLED_APPS = [#Aplicaciones instaladas
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',#imágenes, css y js
    'territorio',#Se debe instalar la aplicación que creemos, esto no se hace automáticamente
]

MIDDLEWARE = [#Va relacionado con las apps instaladas, las librerías que necesita para trabajar los aspectos de seguridad
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sena.urls'

TEMPLATES = [#Admin del backend
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sena.wsgi.application'#Por si se quiere trabajar como una aplicación wsgi o asgi


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [#Reglas para validar los passwords
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'es'#Internacionalización, para organizar el idioma

TIME_ZONE = 'America/Bogota'#fecha y hora

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'#La carpeta donde se van a manejar los staticfiles es esta, se crea (css, html, js, imagenes)

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
