# Generated by Django 4.0.6 on 2022-07-29 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('territorio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(max_length=100)),
                ('fechaInicio', models.DateTimeField()),
                ('fechaFinal', models.DateTimeField()),
                ('aprendiz', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='territorio.aprendiz')),
            ],
        ),
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.CharField(max_length=254)),
                ('observaciones', models.TextField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('monitoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='territorio.monitorias')),
            ],
        ),
    ]
